services:
  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8081:8080"
    container_name: auth-service

  chat-service:
    build:
      context: ./chat-service
    ports:
      - "8080:8080"
    container_name: chat-service

  postgres:
    image: postgres:18.3-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-stomp
    ports:
      - "5672:5672"   # AMQP порт
      - "15672:15672" # Порт для веб-интерфейса управления
      - "61613:61613" # STOMP порт
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_stomp &&
             rabbitmq-server"

volumes:
  postgres_data: