services:
  gateway-service:
    build:
      context: ./gateway
    ports:
      - "8080:8080"
    container_name: gateway-service
    depends_on:
      - auth-service
      - chat-service

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service

  chat-service:
    build:
      context: ./chat-service
    container_name: chat-service

  postgres:
    image: postgres:18.3-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-stomp
    ports:
      - "15672:15672" # Порт для веб-интерфейса управления
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_stomp &&
             rabbitmq-server"

  mongodb:
    image: mongo:7
    container_name: mongodb
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: